[package]
name = "note"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
console = "0.15.1"
crossterm = "0.24.0"
rand = "0.8.5"
text-style = "0.3.0"
tui = "0.18.0"
